In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

course_results = np.array([])

exam_amount = int(input("How many exam have you taken? \n"))
course_exam_amount = np.arange(exam_amount)
for eachloop in range(exam_amount):
    score_of_exam = int( input("Could you enter your "+str(eachloop+1)+ ". exam score: ") )
    course_results = np.append(course_results,score_of_exam )
    print(course_results)
    
    
#course_results = np.array([20,19,20,22,18,25,26,23,29,28,31,32,32,34])
#exam_amount = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

X = course_exam_amount.reshape(-1, 1)  # convert result x to 1 column array
Y = course_results.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column

linear_regressor = LinearRegression()  # Call object
linear_regressor.fit(X, Y)  # Run lilnear regression to given value
Y_pred = linear_regressor.predict(X)  # make prediction
Y_next = linear_regressor.predict(np.array([exam_amount]).reshape(-1,1))
print(str(exam_amount+1)+". Exam's predicted result is: "+ str(Y_next[0]))

plt.scatter(X, Y)
plt.plot(X, Y_pred, color='red')
plt.show()

How many exam have you taken? 
5
Could you enter your 1. exam score: 10
[10.]
Could you enter your 2. exam score: 15
[10. 15.]
Could you enter your 3. exam score: 19
[10. 15. 19.]
Could you enter your 4. exam score: 25
[10. 15. 19. 25.]
Could you enter your 5. exam score: 31
[10. 15. 19. 25. 31.]
6. Exam's predicted result is: [35.6]


<Figure size 640x480 with 1 Axes>